# Generated by Django 4.2.1 on 2023-05-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catergoria',
            fields=[
                ('id_Categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_categoria', models.CharField(max_length=60)),
                ('Descripción', models.TextField(verbose_name=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=60)),
                ('Fecha_de_nacimiento', models.DateField()),
                ('DNI', models.IntegerField()),
                ('Dirección', models.CharField(max_length=100)),
                ('Teléfono', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Nombre_de_usuario', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Rutina',
            fields=[
                ('id_Detalle_Rutina', models.AutoField(primary_key=True, serialize=False)),
                ('Lunes', models.BigIntegerField()),
                ('Martes', models.BigIntegerField()),
                ('Miércoles', models.BigIntegerField()),
                ('Jueves', models.BigIntegerField()),
                ('Viernes', models.BigIntegerField()),
                ('Sábado', models.BigIntegerField()),
                ('Domingo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id_Entrenador', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=60)),
                ('Fecha_de_nacimiento', models.DateField()),
                ('DNI', models.IntegerField()),
                ('Dirección', models.CharField(max_length=100)),
                ('Teléfono', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Nombre_de_usuario', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_Plan', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Por_tiempo', models.BigIntegerField()),
                ('Duración', models.IntegerField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('Vencimiento', models.IntegerField()),
                ('Descripción', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_Proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_proveedor', models.CharField(max_length=60)),
                ('Dirección', models.CharField(max_length=100)),
                ('País', models.CharField(max_length=60)),
                ('Provincia', models.CharField(max_length=60)),
                ('Teléfono', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_Rutina', models.AutoField(primary_key=True, serialize=False)),
                ('Descripción', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rutina_Cliente',
            fields=[
                ('id_Rutina_Cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.cliente')),
                ('id_Rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso_Cliente',
            fields=[
                ('id_Progreso_Cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Peso', models.FloatField()),
                ('Altura', models.FloatField()),
                ('IMC', models.FloatField()),
                ('Observaciones', models.TextField(verbose_name=100)),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.cliente')),
                ('id_Entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_producto', models.CharField(max_length=60)),
                ('Descripción', models.TextField(verbose_name=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Peso', models.FloatField()),
                ('Foto_producto', models.ImageField(upload_to='')),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.catergoria')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Cliente',
            fields=[
                ('id_Plan_Cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha_de_compra', models.DateField()),
                ('Fecha_de_vencimiento', models.DateField()),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.cliente')),
                ('id_Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_Pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('Forma_de_pago', models.CharField(max_length=60)),
                ('Pagado', models.SmallIntegerField()),
                ('Entregado', models.SmallIntegerField()),
                ('Dirección_de_envío', models.CharField(max_length=100)),
                ('Dirección_de_facturación', models.CharField(max_length=100)),
                ('Empresa_envío', models.CharField(max_length=40)),
                ('Nro_guía', models.TextField(verbose_name=40)),
                ('Costo_envío', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('Comprobante_pago', models.IntegerField()),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_Mensaje', models.IntegerField(primary_key=True, serialize=False)),
                ('De', models.CharField(max_length=60)),
                ('Mensaje', models.TextField(verbose_name=100000)),
                ('Fecha', models.DateField()),
                ('Leído', models.SmallIntegerField()),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_Ejercicio', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripción', models.TextField(verbose_name=100)),
                ('Observaciones', models.TextField(verbose_name=100)),
                ('id_Detalle_Rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.detalle_rutina')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_rutina',
            name='id_Rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.rutina'),
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('Código_de_barras', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('Costo_envío', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.pedido')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('id_Detalle_Compra', models.AutoField(primary_key=True, serialize=False)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10, max_length=100)),
                ('id_Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.compra')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='id_Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartFit.proveedor'),
        ),
    ]
